#!/usr/bin/env bash
# on-pre-compact.sh — PreCompact hook for The Next Level Claude fleet.
# Pattern inspired by coleam00/claude-memory-compiler — clean-room
# reimplementation, no code copied.
#
# Fires:   just before Claude Code compacts the conversation context
#          (auto or manual /compact). One last chance to snapshot the
#          recent state before summaries replace raw turns.
# Purpose: write a compressed view of the last ~25 turns into
#          .claude/knowledge/recent-context.md so the post-compact
#          session can re-orient by reading a short file.
#
# Input: common hook JSON on stdin
#   { session_id, transcript_path, cwd, hook_event_name, trigger }
#   trigger ∈ {"manual", "auto"}.
#
# Exit 0 always — never block compaction.

set -uo pipefail

FLEET_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
KB_DIR="$FLEET_DIR/.claude/knowledge"
RECENT_FILE="$KB_DIR/recent-context.md"
HOOK_LOG="$FLEET_DIR/.state/hook-pre-compact.log"
mkdir -p "$KB_DIR" "$(dirname "$HOOK_LOG")"

ts() { date -u +"%Y-%m-%dT%H:%M:%SZ"; }
log() { printf '%s | on-pre-compact | %s\n' "$(ts)" "$*" >> "$HOOK_LOG"; }

PAYLOAD="$(cat 2>/dev/null || true)"
extract() { printf '%s' "$PAYLOAD" | jq -r "$1 // empty" 2>/dev/null || true; }

SESSION_ID="$(extract '.session_id')"
TRANSCRIPT="$(extract '.transcript_path')"
TRIGGER="$(extract '.trigger')"
CWD="$(extract '.cwd')"
[ -z "$SESSION_ID" ] && SESSION_ID="unknown"
[ -z "$TRIGGER" ] && TRIGGER="unknown"

log "fired session=$SESSION_ID trigger=$TRIGGER transcript=$TRANSCRIPT"

# Header for the new snapshot ------------------------------------------------
TMP="$(mktemp 2>/dev/null || echo "/tmp/precompact.$$")"
{
    printf '%s\n\n' '# Recent context snapshot'
    printf '%s\n\n' '<!-- auto-generated by .claude/hooks/on-pre-compact.sh — do not hand-edit -->'
    printf '%s\n' "- snapshot_at: $(ts)"
    printf '%s\n' "- session_id:  $SESSION_ID"
    printf '%s\n' "- trigger:     $TRIGGER"
    [ -n "$CWD" ] && printf '%s\n' "- cwd:         $CWD"
    printf '\n'
} > "$TMP"

# Pull the last 25 user/assistant turns and the last 15 tool uses ------------
if [ -n "$TRANSCRIPT" ] && [ -r "$TRANSCRIPT" ]; then
    {
        printf '## Last user prompts\n\n'
        jq -r --slurpfile _ /dev/null '
            select(.type? == "user")
            | (.message?.content // "")
            | if type == "array" then
                (.[] | select(.type? == "text") | .text)
              else . end
            | select(type == "string")
            | select(length > 0)
            | "- " + (.[0:240] | gsub("\n"; " "))
        ' "$TRANSCRIPT" 2>/dev/null | tail -n 15

        printf '\n## Last assistant turns (truncated)\n\n'
        jq -r '
            select(.type? == "assistant")
            | (.message?.content // [])
            | if type == "array" then
                (.[] | select(.type? == "text") | .text)
              else . end
            | select(type == "string")
            | select(length > 0)
            | "- " + (.[0:240] | gsub("\n"; " "))
        ' "$TRANSCRIPT" 2>/dev/null | tail -n 10

        printf '\n## Recent tool uses\n\n'
        jq -r '
            (.message?.content // [])
            | select(type == "array")
            | .[]
            | select(.type? == "tool_use")
            | "- " + (.name // "?")
              + " "
              + ((.input.file_path // .input.notebook_path // .input.command // .input.url // "")
                 | tostring
                 | .[0:120]
                 | gsub("\n"; " "))
        ' "$TRANSCRIPT" 2>/dev/null | tail -n 15
    } >> "$TMP" 2>/dev/null || log "WARN: transcript parse failed"
else
    printf '## (no transcript available)\n' >> "$TMP"
fi

# Atomic replace -------------------------------------------------------------
if mv "$TMP" "$RECENT_FILE" 2>>"$HOOK_LOG"; then
    log "wrote $RECENT_FILE"
else
    log "WARN: could not write $RECENT_FILE"
    rm -f "$TMP" 2>/dev/null || true
fi

exit 0
